base_url = "https://mhsive.com"

title = "mhs"
description = "missives on building software. meandering thoughts too."
default_language = "en"

# Base
author = "mhs"
compile_sass = true
build_search_index = false

# RSS
generate_feeds = true
taxonomies = [{ name = "tags", rss = true }]

# Theme
theme = "makita"

[markdown]
highlight_code = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false

[extra]
comment = false
math = false
mermaid = false

# The profile on home page.
[extra.profile]
name = "Matt Sutton"
bio = "Product builder. Whiskey drinker. Both at the same time."
avatar_url = "images/oranger.webp"

[[extra.profile.social]]
name = "github"
url = "https://github.com/mhsdef"

[[extra.profile.social]]
name = "codeberg"
url = "https://codeberg.org/mhs"

[[extra.profile.social]]
name = "mastodon"
url = "https://mastodon.social/@mhs"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

[[extra.menu]]
name = "About"
url = "$BASE_URL/about"

[[extra.menu]]
name = "Archive"
url = "$BASE_URL/archive"

[[extra.menu]]
name = "Tags"
url = "$BASE_URL/tags"

[extra.footer]
since = 2010
