title = "mhs"
author = "mhs"
base_url = "https://mhs.dev"
default_language = "en"

# Base
compile_sass = true
build_search_index = false

# RSS
generate_feeds = true
taxonomies = [{ name = "tags", rss = true }]

# Theme
theme = "makita"

[markdown]
highlight_code = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false

[extra]
comment = false
math = false
mermaid = false

# The profile on home page.
[extra.profile]
name = "mhs"
bio = "Product builder. Whiskey drinker. Both at the same time."
avatar_url = "icons/github.svg"
avatar_invert = true

# The `name` should be the file name of static/icons/*.svg or the icon name of https://simpleicons.org/
[[extra.profile.social]]
name = "github"
url = "https://github.com/mhsdef"

[[extra.profile.social]]
name = "mastodon"
url = "https://mastodon.social/@mhs"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

[[extra.menu]]
name = "Archive"
url = "$BASE_URL/archive"

[[extra.menu]]
name = "Tags"
url = "$BASE_URL/tags"

[extra.footer]
since = 2010
